[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
status_hook = "FhCxrWkkKHptVi5zdrT8iHSZTRRjP9E11q9mrTUqNiHR"

[programs.localnet]
status_hook = "FhCxrWkkKHptVi5zdrT8iHSZTRRjP9E11q9mrTUqNiHR"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"
